// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repository/organization (interfaces: OrganizationRepository)
//
// Generated by this command:
//
//	mockgen -package mocks -destination ./internal/mocks/organization/repository.go ./internal/repository/organization OrganizationRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	organization "github.com/uallace-macedo/dev-playbook/golang/unit-tests/internal/model/organization"
	gomock "go.uber.org/mock/gomock"
)

// MockOrganizationRepository is a mock of OrganizationRepository interface.
type MockOrganizationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrganizationRepositoryMockRecorder
	isgomock struct{}
}

// MockOrganizationRepositoryMockRecorder is the mock recorder for MockOrganizationRepository.
type MockOrganizationRepositoryMockRecorder struct {
	mock *MockOrganizationRepository
}

// NewMockOrganizationRepository creates a new mock instance.
func NewMockOrganizationRepository(ctrl *gomock.Controller) *MockOrganizationRepository {
	mock := &MockOrganizationRepository{ctrl: ctrl}
	mock.recorder = &MockOrganizationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrganizationRepository) EXPECT() *MockOrganizationRepositoryMockRecorder {
	return m.recorder
}

// FetchById mocks base method.
func (m *MockOrganizationRepository) FetchById(ct context.Context, id string) (*organization.OrganizationModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchById", ct, id)
	ret0, _ := ret[0].(*organization.OrganizationModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchById indicates an expected call of FetchById.
func (mr *MockOrganizationRepositoryMockRecorder) FetchById(ct, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchById", reflect.TypeOf((*MockOrganizationRepository)(nil).FetchById), ct, id)
}
