"""update order relationships

Revision ID: 3148871d9027
Revises: 999a198e39d0
Create Date: 2026-08-11 19:44:47.223481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3148871d9027'
down_revision: Union[str, Sequence[str], None] = '999a198e39d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tb_orders', 'tb_restaurants', ['restaurant_id'], ['id'])
    op.create_foreign_key(None, 'tb_orders', 'tb_users', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_orders', type_='foreignkey')
    op.drop_constraint(None, 'tb_orders', type_='foreignkey')
    # ### end Alembic commands ###
