"""update reviews add reviewed column

Revision ID: 5ee6ebfe19ea
Revises: 3148871d9027
Create Date: 2026-08-15 10:54:03.430086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ee6ebfe19ea'
down_revision: Union[str, Sequence[str], None] = '3148871d9027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'tb_orders',
        sa.Column(
            'reviewed',
            sa.Boolean(),
            nullable=False,
            server_default=sa.text('false')
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_orders', 'reviewed')
    # ### end Alembic commands ###
