"""add order and order_item relationship

Revision ID: 8a2514bee678
Revises: 3398bd9fb5c0
Create Date: 2026-08-10 22:13:51.042227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a2514bee678'
down_revision: Union[str, Sequence[str], None] = '3398bd9fb5c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_order_items') as batch_op:
        batch_op.create_foreign_key('fk_order_items_product', 'tb_products', ['product_id'], ['id'])
        batch_op.create_foreign_key('fk_order_items_order', 'tb_orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_order_items', type_='foreignkey')
    op.drop_constraint(None, 'tb_order_items', type_='foreignkey')
    # ### end Alembic commands ###
