"""add review restaurant relationship

Revision ID: 999a198e39d0
Revises: dd6c6d5061ba
Create Date: 2026-08-11 18:04:27.356669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '999a198e39d0'
down_revision: Union[str, Sequence[str], None] = 'dd6c6d5061ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tb_restaurants', 'tb_users', ['owner_id'], ['id'])
    op.add_column('tb_reviews', sa.Column('restaurant_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'tb_reviews', 'tb_restaurants', ['restaurant_id'], ['id'])
    op.create_foreign_key(None, 'tb_reviews', 'tb_orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_reviews', type_='foreignkey')
    op.drop_constraint(None, 'tb_reviews', type_='foreignkey')
    op.drop_column('tb_reviews', 'restaurant_id')
    op.drop_constraint(None, 'tb_restaurants', type_='foreignkey')
    # ### end Alembic commands ###
