"""fix review.comment type and add review.customer relationship

Revision ID: dd6c6d5061ba
Revises: 8a2514bee678
Create Date: 2026-08-11 17:36:32.660647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd6c6d5061ba'
down_revision: Union[str, Sequence[str], None] = '8a2514bee678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_reviews', 'comment',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(),
               existing_nullable=True)
    op.create_foreign_key(None, 'tb_reviews', 'tb_users', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_reviews', type_='foreignkey')
    op.alter_column('tb_reviews', 'comment',
               existing_type=sa.String(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###
